In [50]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.base import BaseEstimator, TransformerMixin


# Data
housing = pd.read_csv("datasets/housing/housing.csv")

# Separating into train / test sets 
X = housing.drop('median_house_value', axis = 1)
y = housing['median_house_value']


X_num_attribs = list(X.drop('ocean_proximity', axis = 1).columns)
X_cat_attribs = ['ocean_proximity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)


# Defining pipeline
rooms_ix, bedrooms_ix, population_ix, household_ix = 3,4,5,6
class CombinedAttributesAdder(BaseEstimator,TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True):
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y = None):
        return self
    def transform(self, X, y = None): 
        rooms_per_household = X[:, rooms_ix] / X[:, household_ix] 
        population_per_household = X[:, population_ix] / X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room=  X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

num_pipeline = Pipeline([
                        ('imputer', SimpleImputer(strategy = 'median')),
                        ('attribs_adder', CombinedAttributesAdder()),
                        ('std_scaler', StandardScaler())
])

cat_pipeline = Pipeline([
                        ('one_hot', OneHotEncoder()),
])

full_pipeline = ColumnTransformer([
                            ('num_pipeline', num_pipeline, X_num_attribs),
                            ('cat_pipeline', cat_pipeline, X_cat_attribs)
])

In [51]:
corr_matrix = housing[X_num_attribs].corr(numeric_only=True)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)
print(corr_matrix[abs(corr_matrix) > 0.9])
print()
print('------ High Correlation Pairs ------')
for i, x in enumerate(corr_matrix.columns):
    for y in corr_matrix.columns[i+1:]:
        corr = corr_matrix.loc[x, y]
        if abs(corr) > 0.9:
            print(f'{x} & {y} : {corr}')

                    longitude  latitude  housing_median_age  total_rooms  total_bedrooms  population  households  median_income
longitude            1.000000 -0.924664                 NaN          NaN             NaN         NaN         NaN            NaN
latitude            -0.924664  1.000000                 NaN          NaN             NaN         NaN         NaN            NaN
housing_median_age        NaN       NaN                 1.0          NaN             NaN         NaN         NaN            NaN
total_rooms               NaN       NaN                 NaN     1.000000        0.930380         NaN    0.918484            NaN
total_bedrooms            NaN       NaN                 NaN     0.930380        1.000000         NaN    0.979728            NaN
population                NaN       NaN                 NaN          NaN             NaN    1.000000    0.907222            NaN
households                NaN       NaN                 NaN     0.918484        0.979728    0.907222    1.000000            NaN
median_income             NaN       NaN                 NaN          NaN             NaN         NaN         NaN            1.0

------ High Correlation Pairs ------
longitude & latitude : -0.9246644339150365
total_rooms & total_bedrooms : 0.9303795046865031
total_rooms & households : 0.9184844926543111
total_bedrooms & households : 0.9797282708045709
population & households : 0.9072222660959658

In [52]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.impute import SimpleImputer

numeric_train = pd.DataFrame(
    SimpleImputer(strategy="median").fit_transform(X_train[X_num_attribs]),
    columns=X_num_attribs
)

vif = pd.DataFrame({
    "feature": numeric_train.columns,
    "VIF": [
        variance_inflation_factor(numeric_train.values, i)
        for i in range(numeric_train.shape[1])
    ]
}).sort_values("VIF", ascending=False)

display(vif)

              feature         VIF
0           longitude  615.860685
1            latitude  549.503733
4      total_bedrooms   95.509061
6          households   93.552489
3         total_rooms   30.976826
5          population   16.314986
7       median_income    8.310041
2  housing_median_age    7.266262

I examined pairwise correlations and VIF among numerical predictors. Features with high correlation/VIF were identified as potential sources of multicollinearity. 
Ridge regression was included as L2 regularisation reduces sensitivity to correlated predictors.

In [53]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.metrics import r2_score

# Ridge Tuning
ridge_pipeline = Pipeline([
    ("preprocessing", full_pipeline),
    ("model", Ridge(random_state=42))
])

ridge_grid = {
    'model__alpha': [0.01, 0.1, 1, 10, 100]}

ridge_search = GridSearchCV(
    estimator = ridge_pipeline,
    param_grid = ridge_grid,
    cv=5,
    scoring='r2')

ridge_search.fit(X_train, y_train)

ridge_predictions = ridge_search.predict(X_test)
ridge_test_r2 = r2_score(y_test, ridge_predictions)

print("Best parameters:", ridge_search.best_params_)
print(f"Best cross-validation R²: {ridge_search.best_score_:.3f}")
print(f"Test set R²: {ridge_test_r2:.3f}")

Best parameters: {'model__alpha': 1}
Best cross-validation R²: 0.655
Test set R²: 0.597

In [54]:
# Gradient boosting tuning
gb_pipeline = Pipeline([
    ("preprocessing", full_pipeline),
    ("model", GradientBoostingRegressor(random_state=42))
])

gb_grid = {
    "model__n_estimators": [100, 200, 300],
    "model__max_depth": [2, 3, 4],
    "model__learning_rate": [0.01, 0.05, 0.1]
}

gb_search = GridSearchCV(
    estimator=gb_pipeline,
    param_grid=gb_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1
)

gb_search.fit(X_train, y_train)

gb_predictions = gb_search.predict(X_test)
gb_test_r2 = r2_score(y_test, gb_predictions)

print("Best parameters:", gb_search.best_params_)
print(f"Best cross-validation R²: {gb_search.best_score_:.3f}")
print(f"Test set R²: {gb_test_r2:.3f}")

Best parameters: {'model__learning_rate': 0.1, 'model__max_depth': 4, 'model__n_estimators': 300}
Best cross-validation R²: 0.832
Test set R²: 0.812

In [55]:

final_models = {
    "Linear Regression": Pipeline([
        ("preprocessing", full_pipeline),
        ("model", LinearRegression())
    ]),
    "Decision Tree": Pipeline([
        ("preprocessing", full_pipeline),
        ("model", DecisionTreeRegressor(random_state=42))
    ]),
    "Random Forest": Pipeline([
        ("preprocessing", full_pipeline),
        ("model", RandomForestRegressor(random_state=42))
    ]),
    "Tuned Ridge": ridge_search.best_estimator_,
    "Tuned Gradient Boosting": gb_search.best_estimator_
}

final_results = []

for name, model in final_models.items():
    if name not in ["Tuned Ridge", "Tuned Gradient Boosting"]:
        model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    final_results.append({
        "Model": name,
        "Test set R²": r2_score(y_test, predictions)
    })

final_results_df = pd.DataFrame(final_results).sort_values(
    "Test set R²",
    ascending=False
)

display(final_results_df)

                     Model  Test set R²
4  Tuned Gradient Boosting     0.812405
2            Random Forest     0.806721
1            Decision Tree     0.598903
0        Linear Regression     0.596654
3              Tuned Ridge     0.596550

Gradient Boosting achieved the strongest held-out test R²
The results show that non-linear ensemble methods outperformed the linear baseline on this dataset.